version: '3.8'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      SA_PASSWORD: Aa12345!
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"

  root:
    image: shopping-platform-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mssql